# Generated by GPT to quickly visualize PCA loadings as a heatmap

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

feature_order = [
    # Spatial
    "CoV_velocity_left (m/s) (%)",
    "CoV_velocity_right (m/s) (%)",
    "CoV_stride_length_left (m) (%)",
    "CoV_stride_length_right (m) (%)",

    # Cadence
    "CoV_cadence_left (Hz) (%)",
    "CoV_cadence_right (Hz) (%)",

    # Temporal 
    "CoV_stride_time_left (s) (%)",
    "CoV_stride_time_right (s) (%)",
    "CoV_swing_time_left (s) (%)",
    "CoV_swing_time_right (s) (%)",
    "CoV_stance_time_left (s) (%)",
    "CoV_stance_time_right (s) (%)",

    # Support
    "CoV_single_support_time_left (s) (%)",
    "CoV_single_support_time_right (s) (%)",
    "CoV_double_support_time (s) (%)",
]

# Read PCA loadings
loadings = pd.read_csv("pca_loadings.csv", index_col=0)
loadings = loadings.iloc[:, :4]  # Select the first 4 principal components
loadings = loadings.loc[feature_order]


plt.figure(figsize=(8, 7))

sns.heatmap(
    loadings.where(abs(loadings) > 0.2),
    cmap="coolwarm",
    center=0,
    annot=True,
    fmt=".2f",
    linewidths=0.5,
    cbar_kws={"label": "Loading"}
)

plt.title("PCA Loadings")
plt.xlabel("Principal Components")
plt.ylabel("Gait Features")

plt.tight_layout()
plt.savefig("pca_loadings_heatmap.png", dpi=300)
plt.show()